version: '3.8'

services:
    ecommerce-api-nginx:
        image: nginx:alpine
        container_name: ecommerce-api-nginx
        working_dir: /app
        volumes:
            - ./:/app
            - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 9090:80
        networks:
            - devhack_ecommerce_net

    ecommerce-api-php:
        build: .
        container_name: ecommerce-api-php
        working_dir: /app
        expose:
            - 9000
        volumes:
            - ./:/app
        networks:
            - devhack_ecommerce_net

    ecommerce-api-db:
        image: postgres
        container_name: ecommerce-api-db
        restart: always
        environment:
            POSTGRES_DB: ecommerce_api_db
            POSTGRES_USER: devhack
            POSTGRES_PASSWORD: devhack
        ports:
            - 5737:5432
        networks:
            - devhack_ecommerce_net

networks:
  devhack_ecommerce_net:
      driver: bridge
